export const LANG_META: Record<string, { label: string; monacoLang: string; defaultCode: string }> = {
  javascript: { label: 'JavaScript', monacoLang: 'javascript', defaultCode: 'function solve(input) {\n  // Write your solution here\n  \n}\n' },
  python:     { label: 'Python 3',   monacoLang: 'python',     defaultCode: '# Write your solution inside solve()\ndef solve(data: str):\n    # Write your logic here\n    pass\n' },
  cpp:        { label: 'C++',        monacoLang: 'cpp',        defaultCode: '#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    // --- WRITE YOUR LOGIC BELOW ---\n    // Read from standard input (e.g., cin >> var)\n    // Print to standard output (e.g., cout << var)\n    \n    return 0;\n}\n' },
  java:       { label: 'Java',       monacoLang: 'java',       defaultCode: 'import java.util.*;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner scanner = new Scanner(System.in);\n        \n        // --- WRITE YOUR LOGIC BELOW ---\n        // Read from scanner (e.g., scanner.nextLine())\n        // Print to standard output (e.g., System.out.println())\n        \n    }\n}\n' },
  c:          { label: 'C',          monacoLang: 'c',          defaultCode: '#include <stdio.h>\n\nint main() {\n    // --- WRITE YOUR LOGIC BELOW ---\n    // Read from standard input (e.g., scanf)\n    // Print to standard output (e.g., printf)\n    \n    return 0;\n}\n' },
  csharp:     { label: 'C#',         monacoLang: 'csharp',     defaultCode: 'using System;\n\nclass Program {\n    static void Main() {\n        // --- WRITE YOUR LOGIC BELOW ---\n        // Read from standard input (e.g., Console.ReadLine())\n        // Print to standard output (e.g., Console.WriteLine())\n        \n    }\n}\n' },
  go:         { label: 'Go',         monacoLang: 'go',         defaultCode: 'package main\nimport "fmt"\n\nfunc main() {\n    // --- WRITE YOUR LOGIC BELOW ---\n    // Read from standard input (e.g., fmt.Scan())\n    // Print to standard output (e.g., fmt.Println())\n    \n}\n' },
  rust:       { label: 'Rust',       monacoLang: 'rust',       defaultCode: 'use std::io::{self, Read};\n\nfn main() {\n    // DO NOT EDIT THE INPUT READING CODE\n    let mut input = String::new();\n    io::stdin().read_to_string(&mut input).unwrap();\n    let data = input.trim();\n    \n    // --- WRITE YOUR LOGIC BELOW ---\n    // You can print your output using println!()\n    \n}\n' },
  ruby:       { label: 'Ruby',       monacoLang: 'ruby',       defaultCode: '# DO NOT EDIT THE INPUT READING CODE\ninput_data = STDIN.read.strip\n\n# --- WRITE YOUR LOGIC BELOW ---\n# You can print your output using puts\n\nputs input_data\n' },
};
